# frontend/Dockerfile
FROM nginx:stable-alpine
WORKDIR /usr/share/nginx/html
COPY . .
# Opcional: reemplazar configuración de nginx si quieres servir SPA con history API
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]